[package]
name = "pinephone-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.19.0"
elf = "0.7.2"
gimli = "0.27.2"
lazy_static = "1.4.0"
unicorn-engine = "2.0.0"
